# Generated by Django 3.1.4 on 2021-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
