# Generated by Django 3.1.4 on 2021-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20210312_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(),
        ),
    ]
