# Generated by Django 3.1.4 on 2021-03-13 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20210312_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
