# Generated by Django 3.1.4 on 2021-03-13 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20210312_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
