# Generated by Django 3.1.4 on 2021-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210124_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default=1),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateField(default=1),
        ),
    ]
