# Generated by Django 3.1.4 on 2021-01-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20210127_0237'),
        ('blog', '0019_auto_20210124_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
