# Generated by Django 3.1.4 on 2021-01-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210128_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='pic',
        ),
    ]
