# Generated by Django 3.1.4 on 2021-01-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20210127_0237'),
        ('blog', '0022_remove_comments_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(default=None,null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
