# Generated by Django 3.1.4 on 2021-01-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20210127_0237'),
        ('blog', '0024_auto_20210129_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
