# Generated by Django 3.1.4 on 2021-01-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20210127_0237'),
        ('blog', '0025_auto_20210129_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='profile',
        ),
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ManyToManyField(to='home.userprofile'),
        ),
    ]
