# Generated by Django 3.1.4 on 2021-02-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='head0',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head0para',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head1para',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2para',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='para1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='postimgdesc',
        ),
    ]
