# Generated by Django 3.1.4 on 2021-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210219_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
