# Generated by Django 3.1.4 on 2021-01-10 14:25

import datetime
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210110_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default="2021-01-24"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default="2021-01-24 "),
        ),
    ]
