# Generated by Django 3.1.4 on 2021-01-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210110_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='contacted_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
