# Generated by Django 3.1.4 on 2021-01-24 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210124_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacted_at',
            field=models.DateField(default="2021-01-24"),
        ),
    ]
