# Generated by Django 3.1.4 on 2021-01-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210124_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted_at',
        ),
    ]
