# Generated by Django 3.1.4 on 2021-01-24 11:54

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20210124_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacted',
            field=models.DateTimeField(default="2021-01-24 "),
        ),
    ]
