# Generated by Django 3.1.4 on 2021-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210124_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacted',
            field=models.DateTimeField(default="2021-01-24 "),
        ),
    ]
