# Generated by Django 3.1.4 on 2021-01-24 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210124_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted',
        ),
        migrations.AddField(
            model_name='contact',
            name='contacted_at',
            field=models.DateTimeField(default="2021-01-24 "),
        ),
    ]
