# Generated by Django 3.1.4 on 2021-01-24 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20210124_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacted_at',
            field=models.DateTimeField(default="2021-01-24 04:12:52.268804"),
        ),
    ]
