# Generated by Django 3.1.4 on 2021-01-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20210125_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted_at',
        ),
    ]
