# Generated by Django 3.1.4 on 2021-01-25 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_remove_contact_contacted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contacted_at',
            field=models.DateField(default="2021-01-24"),
            preserve_default=False,
        ),
    ]
