# Generated by Django 3.1.4 on 2021-01-25 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_auto_20210125_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
