# Generated by Django 3.1.4 on 2021-01-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
