# Generated by Django 3.1.4 on 2021-01-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20210125_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
