# Generated by Django 3.1.4 on 2021-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_auto_20210125_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
