# Generated by Django 3.1.4 on 2021-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20210125_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
