# Generated by Django 3.1.4 on 2021-01-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20210126_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
