# Generated by Django 3.1.4 on 2021-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_auto_20210126_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sno',
            field=models.AutoField( primary_key=True, serialize=False, unique=True,default=None),
        ),
    ]
