# Generated by Django 3.1.4 on 2021-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_auto_20210127_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='home/images'),
        ),
    ]
