# Generated by Django 3.1.4 on 2021-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_auto_20210209_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacted_at',
            field=models.DateField(null=True),
        ),
    ]
