# Generated by Django 3.1.4 on 2021-02-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_auto_20210216_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted_at',
        ),
    ]
