# Generated by Django 3.1.4 on 2021-02-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_remove_contact_contacted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
