# Generated by Django 3.1.4 on 2021-03-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_auto_20210216_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
